### ISSUE TITLE
Generation problem

### ISSUE THREAD

**Issue by malish8632** [prius/leetcode-anki#6]
Hi @prius, tried to generate and got this error:

test ! "x/Users/user/Downloads/leetcode-anki/leetcode-anki" = "x" || (echo "Need to run inside venv" && exit 1)
pip install -r requirements.txt
Requirement already satisfied: python-leetcode in ./leetcode-anki/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.0.6)
Requirement already satisfied: diskcache in ./leetcode-anki/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (5.2.1)
Requirement already satisfied: genanki in ./leetcode-anki/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: tqdm in ./leetcode-anki/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.62.3)
Requirement already satisfied: certifi in ./leetcode-anki/lib/python3.9/site-packages (from python-leetcode->-r requirements.txt (line 1)) (2021.10.8)
Requirement already satisfied: urllib3>=1.15 in ./leetcode-anki/lib/python3.9/site-packages (from python-leetcode->-r requirements.txt (line 1)) (1.26.7)
Requirement already satisfied: python-dateutil in ./leetcode-anki/lib/python3.9/site-packages (from python-leetcode->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: six>=1.10 in ./leetcode-anki/lib/python3.9/site-packages (from python-leetcode->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: cached-property in ./leetcode-anki/lib/python3.9/site-packages (from genanki->-r requirements.txt (line 3)) (1.5.2)
Requirement already satisfied: pyyaml in ./leetcode-anki/lib/python3.9/site-packages (from genanki->-r requirements.txt (line 3)) (6.0)
Requirement already satisfied: frozendict in ./leetcode-anki/lib/python3.9/site-packages (from genanki->-r requirements.txt (line 3)) (2.0.6)
Requirement already satisfied: pystache in ./leetcode-anki/lib/python3.9/site-packages (from genanki->-r requirements.txt (line 3)) (0.5.0)
python3 generate.py
Traceback (most recent call last):
  File "/Users/user/Downloads/leetcode-anki/generate.py", line 14, in <module>
    import genanki  # type: ignore
  File "/Users/user/Downloads/leetcode-anki/leetcode-anki/lib/python3.9/site-packages/genanki/__init__.py", line 6, in <module>
    from .model import Model
  File "/Users/user/Downloads/leetcode-anki/leetcode-anki/lib/python3.9/site-packages/genanki/model.py", line 3, in <module>
    import pystache
  File "/Users/user/Downloads/leetcode-anki/leetcode-anki/lib/python3.9/site-packages/pystache/__init__.py", line 2, in <module>
    from init import *
ModuleNotFoundError: No module named 'init'
make: *** [generate] Error 1

**Comment by prius** [comment]
Hi @malish8632! Sorry, I haven't tested it for Windows. I don't have a working windows system and I don't know if I will. You can debug it yourself and submit a PR if you wish, but I can't guarantee you to fix it myself, sorry.

It looks like the problem is actually in `pystash` module. I'd recommend to import it directly and see if it still fails. In this case I'd report a bug to https://github.com/defunkt/pystache

**Comment by Klaudioz** [comment]
Happy to help. I've created the PR 👍🏻
